// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14oegRAij5vMHBkWqZiVvkcpGoa3yj-o',
    appId: '1:251736965971:web:487a9143625640559497a6',
    messagingSenderId: '251736965971',
    projectId: 'flutter-firebase-setup-demo',
    authDomain: 'flutter-firebase-setup-demo.firebaseapp.com',
    storageBucket: 'flutter-firebase-setup-demo.firebasestorage.app',
    measurementId: 'G-HGV0G1FFFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKCtBUhQklfkW9iPHb9tvcwTCWVXBiNI',
    appId: '1:251736965971:android:3ce62d0518dfff129497a6',
    messagingSenderId: '251736965971',
    projectId: 'flutter-firebase-setup-demo',
    storageBucket: 'flutter-firebase-setup-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbdvYSv6Y5vYb7HKURnL7QP9BzlyFchWk',
    appId: '1:251736965971:ios:f76db8a2f4c3d7e89497a6',
    messagingSenderId: '251736965971',
    projectId: 'flutter-firebase-setup-demo',
    storageBucket: 'flutter-firebase-setup-demo.firebasestorage.app',
    iosClientId: '251736965971-2fh913otkeionjoc6nvg40ktgk7j1kbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseServicesDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbdvYSv6Y5vYb7HKURnL7QP9BzlyFchWk',
    appId: '1:251736965971:ios:f76db8a2f4c3d7e89497a6',
    messagingSenderId: '251736965971',
    projectId: 'flutter-firebase-setup-demo',
    storageBucket: 'flutter-firebase-setup-demo.firebasestorage.app',
    iosClientId: '251736965971-2fh913otkeionjoc6nvg40ktgk7j1kbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseServicesDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD14oegRAij5vMHBkWqZiVvkcpGoa3yj-o',
    appId: '1:251736965971:web:0a52878200c71c749497a6',
    messagingSenderId: '251736965971',
    projectId: 'flutter-firebase-setup-demo',
    authDomain: 'flutter-firebase-setup-demo.firebaseapp.com',
    storageBucket: 'flutter-firebase-setup-demo.firebasestorage.app',
    measurementId: 'G-CCECN7J7TX',
  );
}
